name: Deploy

on:
  push:
    branches: [ master ]
    paths-ignore:
      # Git and GitHub
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.**'
      # schedule-specific
      - 'config.default.php'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        # Connection
        server: ${{ secrets.FTP_SERVER }}
        protocol: ${{ secrets.FTP_PROTOCOL }}
        server-dir: ${{ secrets.FTP_SERVERDIR }}
        # Login
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        # Exludes
        exclude: README.**
          - **/.README.**
          - LICENSE
          - config.default.php
         
        # The local folder to copy, defaults to root project folder
        # local-dir: # optional, default is ./
